"use client";

import { useState } from "react";
import { createParticipant, createRequest, createSpace, fetchActivity, fetchSpaces, fundSpace, type ParticipantKind } from "@/lib/contract";
import { CardRise } from "@/components/motion";
import { SectionIntro } from "@/components/app/SectionIntro";
import { useAppData } from "@/lib/app-data";

const STEPS = [
  { key: "connect", title: "Connect", copy: "Confirm the API is reachable and return the current Space." },
  { key: "create", title: "Create", copy: "Create a Space when none exists, or continue with the active one." },
  { key: "roster", title: "Roster", copy: "Add a participant with one of the contract's five kinds." },
  { key: "fund", title: "Fund", copy: "Capitalize the treasury before the first bounded request." },
  { key: "request", title: "First request", copy: "Create the first request and make the loop visible." },
] as const;
type StepKey = (typeof STEPS)[number]["key"];

export function OnboardingWizard({ embedded = false }: { embedded?: boolean } = {}) {
  const { space, spaceId, participants, requests, refresh, loading, error } = useAppData();
  const [active, setActive] = useState<StepKey>("connect");
  const [status, setStatus] = useState<Record<string, string>>({});
  const [name, setName] = useState("My Space"); const [kind, setKind] = useState<ParticipantKind>("Human"); const [displayName, setDisplayName] = useState("Teammate"); const [amount, setAmount] = useState("500.00"); const [title, setTitle] = useState("First bounded request");
  const setResult = (key: string, value: string) => setStatus((current) => ({ ...current, [key]: value }));
  const run = async (key: StepKey) => { setActive(key); setResult(key, "Checking…"); try { if (key === "connect") { const spaces = await fetchSpaces(); setResult(key, spaces.length ? `Connected · ${spaces.length} Space${spaces.length === 1 ? "" : "s"} visible` : "Connected · no Spaces yet"); } else if (key === "create") { const spaces = await fetchSpaces(); if (spaces.length) setResult(key, "A Space already exists — continuing with it."); else { const created = await createSpace({ name, description: "Created from the onboarding wizard", actorId: "admin-01" }); setResult(key, `Created ${created.id}. Refresh to continue.`); await refresh(); } } else if (key === "roster") { if (participants.length) setResult(key, "Roster has active participants — no addition needed."); else { const participant = await createParticipant(spaceId, { kind, displayName, actorId: "admin-01" }); setResult(key, `Added ${participant.displayName} (${participant.kind}).`); await refresh(); } } else if (key === "fund") { const updated = await fundSpace(spaceId, amount, "admin-01"); setResult(key, `Funded ${amount} USDC · balance ${updated.balance}.`); await refresh(); } else { if (requests.length) setResult(key, "A request already exists — the first step is complete."); else { const request = await createRequest(spaceId, { createdBy: "admin-01", title, instructions: "Created from onboarding" }); setResult(key, `Created ${request.requestId}.`); await refresh(); } } } catch (reason) { setResult(key, reason instanceof Error ? reason.message : "Precondition failed."); } };
  const currentIndex = STEPS.findIndex((step) => step.key === active);
  return <section className={`app-section app-section--wizard ${embedded ? "app-section--embedded" : ""}`} id="onboarding"><div className="container">{!embedded && <SectionIntro eyebrow="ONBOARDING" segments={[{ text: "Five steps to a" }, { text: "working Space", accent: true }, { text: "." }]} copy="Each step pre-checks its precondition. If the API cannot advance the step, the wizard explains what is missing instead of leaving a dead button." />}{error && <div className="action-flash action-flash--danger">{error}</div>}<div className="wizard-grid"><CardRise className="wizard-steps"><div className="wizard-step-list">{STEPS.map((step, index) => <button key={step.key} className={`wizard-step ${active === step.key ? "is-active" : ""}`} onClick={() => setActive(step.key)}><span className="font-ui">0{index + 1}</span><strong>{step.title}</strong><span className="muted">{step.copy}</span>{status[step.key] && <em>{status[step.key]}</em>}</button>)}</div></CardRise><CardRise delay={0.18} className="wizard-panel"><div className="wizard-panel__top"><span className="eyebrow">STEP {String(currentIndex + 1).padStart(2, "0")} / 05</span><span className="font-ui muted" style={{ fontSize: 10 }}>{STEPS[currentIndex].key.toUpperCase()}</span></div><h3>{STEPS[currentIndex].title}</h3><p className="muted">{STEPS[currentIndex].copy}</p>{active === "connect" && <div className="wizard-readout"><strong>{space?.name ?? "No active Space"}</strong><span>{space ? space.network : "Waiting for API"}</span></div>}{active === "create" && <label className="wizard-field">SPACE NAME<input value={name} onChange={(event) => setName(event.target.value)} /></label>}{active === "roster" && <div className="wizard-fields"><label className="wizard-field">PARTICIPANT<input value={displayName} onChange={(event) => setDisplayName(event.target.value)} /></label><label className="wizard-field">KIND<select value={kind} onChange={(event) => setKind(event.target.value as ParticipantKind)}><option>Human</option><option>Agent</option><option>Service</option><option>Organization</option><option>Counterparty</option></select></label></div>}{active === "fund" && <label className="wizard-field">AMOUNT (USDC)<input value={amount} onChange={(event) => setAmount(event.target.value)} inputMode="decimal" /></label>}{active === "request" && <label className="wizard-field">REQUEST TITLE<input value={title} onChange={(event) => setTitle(event.target.value)} /></label>}<div className="wizard-actions"><button className="wizard-run" onClick={() => void run(active)} disabled={loading}>{loading ? "Checking…" : "Run precheck"}</button><button className="wizard-next" disabled={currentIndex >= STEPS.length - 1} onClick={() => setActive(STEPS[currentIndex + 1].key)}>Next step →</button></div>{status[active] && <div className={`wizard-result ${status[active].startsWith("Checking") ? "" : "is-done"}`}>{status[active]}</div>}</CardRise></div></div></section>;
}
